spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatisplus?useSSL=false&characterEncoding=utf-8&serverTimezome=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root


