server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          predicates:  #断言失败的话404
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由
            - After=2022-07-24T00:53:41.651+08:00[Asia/Shanghai] #在指定的时间之后才进行路由
            - Before=2023-07-24T00:53:41.651+08:00[Asia/Shanghai] #在指定的时间之前才进行路由
            - Between=2022-07-24T00:53:41.651+08:00[Asia/Shanghai],2023-07-24T00:53:41.651+08:00[Asia/Shanghai] #在指定的时间之间才进行路由
            - Cookie=language,java #请求带cookie且cookie的键为language值为java，值可以用正则表达式匹配
            - Header=haha,hehe #请求头要有haha属性并且值为hehe才进行路由，值可以用正则表达式匹配
            - Host=**.atguigu.com,**.atguigu.com #指定一组匹配的域名列表
            - Method=GET #只有get请求才路由
            - Query=username,xiaobai #支持传入两个参数，一个是属性名，一个为属性值，属性值可以是正则表达式。

          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE      #匹配后提供服务的路由地址

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE      #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由

        - id : baidu_news_guonei
          predicates:
            - Path=/guonei
          uri: http://news.baidu.com/guonei

eureka:
  instance:
    hostname: cloud-gateway-service
    instance-id: cloud-gateway
    prefer-ip-address: true
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
