server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: hystrix-order80
    prefer-ip-address: true #访问地址显示ip

feign:
  hystrix:
    enabled: true